### Study hours and Marks  Prediction using linear regression

### Data Preprocessing

### Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### import Dataset

In [2]:
dataset=pd.read_csv('student_scores.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [3]:
print(dataset)

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86


### Spliting data

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=0)

In [5]:
print(X_train)

[[3.8]
 [1.9]
 [7.8]
 [6.9]
 [1.1]
 [5.1]
 [7.7]
 [3.3]
 [8.3]
 [9.2]
 [6.1]
 [3.5]
 [2.7]
 [5.5]
 [2.7]
 [8.5]
 [2.5]
 [4.8]
 [8.9]
 [4.5]]


In [6]:
print(Y_train)

[35 24 86 76 17 47 85 42 81 88 67 30 25 60 30 75 21 54 95 41]


In [7]:
print(X_test)

[[1.5]
 [3.2]
 [7.4]
 [2.5]
 [5.9]]


In [8]:
print(Y_test)

[20 27 69 30 62]


### Linear regression Model

In [9]:
from sklearn.linear_model import LinearRegression 

In [10]:
linear_model=LinearRegression()

In [11]:
linear_model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

### prediction

In [13]:
y_pred = linear_model.predict(X_test)

In [14]:
print(y_pred)

[16.88414476 33.73226078 75.357018   26.79480124 60.49103328]


### 

In [ ]:
# Visulising the Result (Training_Set)
plt.scatter(X_train,y_train, color= 'red')
plt.plot(X_train, linear_reg.predict(X_train), color= 'blue' )
plt.title('Salary Prediction')
plt.xlabel('Years Experince')
plt.ylabel('Salary')
plt.show()